# Generated by Django 3.0.7 on 2020-07-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=35)),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='articles/images')),
            ],
        ),
    ]
