# Generated by Django 3.0.7 on 2020-07-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=45)),
                ('author', models.CharField(default='Anonymous', max_length=20, null=True)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(default='Nothing here...')),
                ('date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='articles/images')),
            ],
        ),
    ]
