# Generated by Django 3.0.7 on 2020-07-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_info',
            name='email',
            field=models.CharField(default='', max_length=45),
        ),
    ]
