# Generated by Django 3.0.7 on 2020-07-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_all_info_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_info',
            name='content',
            field=models.CharField(default='Nothing Here.', max_length=1000),
        ),
    ]
