# Generated by Django 3.0.7 on 2020-07-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_all_info_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_info',
            name='author',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
