# Generated by Django 3.0.7 on 2020-07-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200711_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_info',
            name='author',
            field=models.CharField(default='Anonymous', max_length=35),
        ),
    ]
