# Generated by Django 3.0.7 on 2020-07-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200711_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_info',
            name='author',
            field=models.CharField(default='Anonymous', max_length=35, null=True),
        ),
    ]
