# Generated by Django 3.0.7 on 2020-07-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200711_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_info',
            name='author',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
    ]
