# Generated by Django 3.0.7 on 2020-07-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200711_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_info',
            name='author',
            field=models.CharField(default='Anonymous', max_length=20, null=True),
        ),
    ]
