# Generated by Django 3.0.7 on 2020-07-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200712_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_info',
            name='content',
            field=models.CharField(default='Nothing Here...', max_length=100000000000),
        ),
    ]
