# Generated by Django 3.0.7 on 2020-07-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200712_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_info',
            name='content',
            field=models.TextField(default='Nothing here...'),
        ),
    ]
